# Generated by Django 5.0.2 on 2024-03-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
    ]
