# Generated by Django 5.0.2 on 2024-03-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
